from flask import Flask, jsonify, request
from flask_cors import CORS
import pandas as pd
import numpy as np
import os

app = Flask(__name__)
CORS(app)  # Enable CORS for all routes

# Define paths
DATA_DIR = os.path.join(os.path.dirname(__file__), '../data')

def get_data_path(filename):
    return os.path.join(DATA_DIR, filename)

@app.route('/api/status', methods=['GET'])
def status():
    return jsonify({"status": "healthy", "service": "Brent Oil Analysis API"})

@app.route('/api/data', methods=['GET'])
def get_historical_data():
    """
    Returns historical Brent oil prices.
    Query params: start_date, end_date (optional)
    """
    try:
        # Try to read processed data first, then raw
        file_path = get_data_path('BrentOilPrices_Processed.csv')
        if not os.path.exists(file_path):
            file_path = get_data_path('BrentOilPrices.csv')

        if not os.path.exists(file_path):
            # Return dummy data if file missing (for dev purposes)
            dates = pd.date_range(start='2020-01-01', end='2022-01-01', freq='W')
            df = pd.DataFrame({'Date': dates, 'Price': np.random.rand(len(dates))*50 + 50})
        else:
            df = pd.read_csv(file_path)
            # Ensure Date column is handled correctly
            if 'Date' not in df.columns and df.index.name == 'Date':
                df = df.reset_index()

            # Basic date parsing handling
            try:
                df['Date'] = pd.to_datetime(df['Date'], format='%d-%b-%y')
            except:
                df['Date'] = pd.to_datetime(df['Date'])

        # Start/End date filtering
        start_date = request.args.get('start_date')
        end_date = request.args.get('end_date')

        if start_date:
            df = df[df['Date'] >= pd.to_datetime(start_date)]
        if end_date:
            df = df[df['Date'] <= pd.to_datetime(end_date)]

        # Convert to JSON friendly format (list of dicts or lists)
        # Recharts often prefers list of objects: [{date: '...', price: 10}, ...]
        data = df[['Date', 'Price']].copy()
        data['Date'] = data['Date'].dt.strftime('%Y-%m-%d')
        result = data.to_dict(orient='records')

        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/events', methods=['GET'])
def get_events():
    """Returns the list of key geopolitical events."""
    try:
        file_path = get_data_path('events_template.csv')
        if not os.path.exists(file_path):
             return jsonify([])

        df = pd.read_csv(file_path)
        # Parse dates just to be safe they are valid, then format back
        df['Date'] = pd.to_datetime(df['Date'])
        df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

        return jsonify(df.to_dict(orient='records'))
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/changepoints', methods=['GET'])
def get_changepoints():
    """
    Returns detected change points.
    In a real scenario, this would read from a results file generated by the notebook.
    For now, we mock it or read a placeholder.
    """
    # Mock response for dashboard development
    # Ideally, the notebook should save 'change_points.json' to the data folder
    mock_changepoints = [
        {"date": "2020-03-11", "type": "Shock", "description": "COVID-19 Declaration", "impact": "-30%"},
        {"date": "2022-02-24", "type": "Shock", "description": "Russia-Ukraine War", "impact": "+25%"}
    ]
    return jsonify(mock_changepoints)

if __name__ == '__main__':
    app.run(debug=True, port=5000)
